### ISSUE TITLE
Plugin giving a 504 after 60seconds

### ISSUE THREAD

**Issue by apr-1985** [lsjostro/prometheus-plugin#2]
Hello.
I have installed the prometheus-plugin on my Jenkins server (Jenkins version 2.7.20.2).
However when I try to hit /prometheus my browser tries for a minute and then gets a 504 The server didn't respond in time.

Any ideas why this maybe happening?

Cheers

**Comment by lsjostro** [comment]
Hi @apr-1985! 
Please add the issue to jenkinsci/prometheus-plugin repo so others can help!

Cheers,
Lars
