### ISSUE TITLE
Error introduced between 2.0.8 and 2.0.10

### ISSUE THREAD

**Issue by MrDecisive** [lsjostro/prometheus-plugin#6]
Hi,

We recently updated this plugin to 2.0.10 and now we see this error in the journalctl -u telegraf logs:

**telegraf[7915]: 2021-04-20T13:52:30Z E! [inputs.prometheus] Error in plugin: error reading metrics for http://<host>/prometheus/: reading text format failed: text format parsing error in line 1394: second TYPE line for metric name "jenkins_node_builds", or TYPE reported after samples**

I've tested this with a different installation of telegraf to the same jenkins intance and it reports the same error.

I've tested using the same telegraf and an instance of jenkins where the plugin has not been upgraded and there is no error.

This suggests the upgrade version is the culprit.

Any thoughts?

Cheers
Phill

**Comment by lsjostro** [comment]
Hi @MrDecisive please create the issue here https://github.com/jenkinsci/prometheus-plugin

**Comment by MrDecisive** [comment]
Yep sure will do
